### ISSUE TITLE
Missing timestamp

### ISSUE THREAD

**Issue by rubenstolk** [choonkeat/heroku-log-s3#5]
The (request) logs written to S3 don't include the original timestamp, which makes them kind of useless?

**Comment by rubenstolk** [comment]
@choonkeat any thoughts on this?

**Comment by choonkeat** [comment]
unfortunately i haven't been using heroku, ruby, and this project for a while now

though if the original logs has timestamps, then the lines shipped to s3 should carry timestamps too? otherwise, you might want to try sticking in a timestamp before `line` https://github.com/choonkeat/heroku-log-s3/blob/835539a8f6029f43f70cca3d94fb5c35a1f8c780/writer/base.rb#L18-L20

**Comment by choonkeat** [comment]
Closed by #6
